env:
    browser: true
    es6: true
extends: 'eslint:recommended'
plugins:
    - "vue"
parserOptions:
    sourceType: module
rules:
    indent:
        - error
        - tab
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-console:
        - off
